// <auto-generated />
namespace Garage2._00.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Search8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Search8));
        
        string IMigrationMetadata.Id
        {
            get { return "201802140910134_Search8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
